# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: index.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='index.proto',
  package='anndb_pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bindex.proto\x12\x08\x61nndb_pb\"\x10\n\x0eVertexMetadatab\x06proto3'
)




_VERTEXMETADATA = _descriptor.Descriptor(
  name='VertexMetadata',
  full_name='anndb_pb.VertexMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=41,
)

DESCRIPTOR.message_types_by_name['VertexMetadata'] = _VERTEXMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VertexMetadata = _reflection.GeneratedProtocolMessageType('VertexMetadata', (_message.Message,), {
  'DESCRIPTOR' : _VERTEXMETADATA,
  '__module__' : 'index_pb2'
  # @@protoc_insertion_point(class_scope:anndb_pb.VertexMetadata)
  })
_sym_db.RegisterMessage(VertexMetadata)


# @@protoc_insertion_point(module_scope)
