# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import search_pb2 as search__pb2


class SearchStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_stream(
                '/anndb_pb.Search/Search',
                request_serializer=search__pb2.SearchRequest.SerializeToString,
                response_deserializer=search__pb2.SearchResultItem.FromString,
                )
        self.SearchPartitions = channel.unary_stream(
                '/anndb_pb.Search/SearchPartitions',
                request_serializer=search__pb2.SearchPartitionsRequest.SerializeToString,
                response_deserializer=search__pb2.SearchResultItem.FromString,
                )


class SearchServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchPartitions(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_stream_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=search__pb2.SearchRequest.FromString,
                    response_serializer=search__pb2.SearchResultItem.SerializeToString,
            ),
            'SearchPartitions': grpc.unary_stream_rpc_method_handler(
                    servicer.SearchPartitions,
                    request_deserializer=search__pb2.SearchPartitionsRequest.FromString,
                    response_serializer=search__pb2.SearchResultItem.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'anndb_pb.Search', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Search(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/anndb_pb.Search/Search',
            search__pb2.SearchRequest.SerializeToString,
            search__pb2.SearchResultItem.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchPartitions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/anndb_pb.Search/SearchPartitions',
            search__pb2.SearchPartitionsRequest.SerializeToString,
            search__pb2.SearchResultItem.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
